---
- name: Setup Personal
  include_role:
    name: base

- name: Setup git clone env
  copy:
    dest: {{home_directory}}/.gitcloneenv
    content: |
      GIT_CLONE_DEFAULT_PROJECT={{github_project}}
