---
# setup my macbook just the way I like it

- hosts: mac
  roles:
    - expedia
  vars_prompt:
    - name: password
      prompt: "What is your password?"
      private: yes
#      encrypt: "sha512_crypt"
#      confirm: yes
#      salt_size: 7
