- name: Change login shell
  become_user: "{{user}}}}"
  command: chsh -s /usr/local/bin/bash

- name: Add ssh passphrase
  command: ssh-keygen -p -f "{{home_directory}}/.ssh/id_rsa"

- name: Setup ssh-agent
  shell: eval "$(ssh-agent -s)" && ssh-add -K "{{home_directory}}/.ssh/id_rsa"

- name: Add public key to GitHub
  shell: curl -fsSL -u 'rob@lidalia.org.uk' -X POST -d '{"title":"{{location}} {{mac_model}}","key":"ssh-rsa AAA..."}' 'https://api.github.com/user/keys'
