---
# getting my dotfile configuration

- name: Ensure presence of bash_profile
  file: state=touch path={{home_directory}}/.bash_profile

- name: Load bashrc in bash_profile
  lineinfile: dest={{home_directory}}/.bash_profile regexp="\. \$HOME\/\.bashrc" line="[[ -r $HOME/.bashrc ]] && . $HOME/.bashrc"

- name: Copy in bashrc
  template: src=templates/bashrc dest={{home_directory}}/.bashrc

- name: Ensure presence of local bin
  file: state=directory recurse=yes path={{home_directory}}/local/bin

- name: Add local bin to $PATH
  lineinfile: dest={{home_directory}}/.bashrc regexp="^export PATH\=\$HOME\/local\/bin" line="export PATH=$HOME/local/bin:$PATH"

- name: Copy in git config
  template: src=templates/git-config dest={{home_directory}}/.gitconfig

- name: Copy in global git ignore
  copy: src=dotfiles/gitignore_global dest={{home_directory}}/.gitignore_global

- name: Copy in .inputrc
  copy: src=dotfiles/inputrc dest={{home_directory}}/.inputrc

- name: Copy in .vimrc
  copy: src=dotfiles/vimrc dest={{home_directory}}/.vimrc

- name: Copy in scripts
  copy:
    src: scripts/
    dest: "{{home_directory}}/local/bin"
    owner: "{{user}}"
    group: "staff"
    mode: '0755'

- name: Register bash 4+
  become: yes
  lineinfile:
    dest: /etc/shells
    insertafter: EOF
    line: /usr/local/bin/bash
    state: present
  notify: Change login shell
