---
- name: Setup Expedia
  include_role:
    name: base
    public: yes

- name: Setup git clone env
  copy:
    dest: "{{home_directory}}/.gitcloneenv"
    content: |
      GIT_CLONE_DEFAULT_HOST={{github_host}}
      GIT_CLONE_DEFAULT_PROJECT={{github_project}}

- name: maven
  include: maven.yml

- name: tap homebrew AdoptOpenJDK/openjdk
  homebrew_tap:
    tap: Brand-Expedia/homebrew-tools
    url: git@github.expedia.biz:Brand-Expedia/homebrew-tools.git

- name: Get Artifactory token
  shell: "{{ password }} | curl -u {{ user }} --silent --show-error -K --fail https://artylab.expedia.biz/api/security/encryptedPassword"
  register: arty_token

- name: aws_keygen
  environment:
    HOMEBREW_ARTIFACTORY_API_TOKEN: "{{ arty_token.stdout }}"
  homebrew:
    name: aws_key_gen
    state: latest

- name: install aws
  environment:
    HOMEBREW_ARTIFACTORY_API_TOKEN: "{{ arty_token.stdout }}"
  homebrew:
    name: aws_key_gen
    state: latest
