export BASH_COMPLETION_COMPAT_DIR="$(brew --prefix)/etc/bash_completion.d"
[[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"

export CLICOLOR=1
export LSCOLORS=exGxBxDxCxEgEdxbxgxcxd

GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_SHOWUPSTREAM=auto
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWSTASHSTATE=true

PROMPT_COMMAND='__git_ps1 "\u@\h:\w" "\\\$ "'

complete -C /usr/local/bin/vault vault

alias ll='ls -lAh'

export JAVA_OPTS=-Dapple.awt.UIElement=true

setJava() {
  export JAVA_HOME="$(/usr/libexec/java_home -v $1)"
}

alias j8="setJava 1.8"
alias j11="setJava 11"
alias j13="setJava 13"

if [ -e .java_version ]; then
    javaVersion="$(cat .java_version)"
else
    javaVersion="13"
fi

setJava "$javaVersion"
